---
- name: Gather list of target machines
  azure.azcollection.azure_rm_virtualmachine_info:
    subscription_id: "{{ subscription_id }}"
    resource_group: "WEM-CUSTOMERS-RG-1"
    name: "customer-09d3nu1yo5x1-console-cloud124build6222"
  register: search_results

- debug:
    var: search_results

- name: Fail if search_results yields nothing
  fail:
    msg: "No results"
  when: search_results.vms | length == 0

- name: Create list of all targeted servers based on filters above
  set_fact:
    target_machines: "{{ search_results.vms }}"

- name: List VM info
  loop: '{{ target_machines }}'
  loop_control:
    loop_var: current_instance
    debug:
      var_1: current_instance.os_type
      var_2: current_instance.image.id
      var_3: current_instance.image.offer
      var_4: current_instance.image.sku
