---

- debug:
    var: search_results

- name: Fail if search_results yields nothing
  fail:
    msg: "No results"
  when: search_results.vms | length == 0

- name: Create list of all targeted servers based on filters above
  set_fact:
    target_machines: "{{ search_results.vms }}"

- debug:
    var: target_machines
